### PR TITLE
Folder restructure and easier asset use

### PR DESCRIPTION
**Pull request by GammaGames**
(Based on PR https://github.com/rpgwhitelock/AllSkyFree_Godot/pull/1)

* Move into `asset/AllSkyFree` folder for submission to asset library
* Move demo scenes into own folder
* Move `WorldEnvironment` and `DirectionalLight` nodes into own scenes for easy import into existing scenes
* Fix small node naming issue in several scenes

### CODE REVIEW

**Comment by GammaGames** [comment]
This shouldn't be merged until PR #1 is, as it would probably cause conflicts

**Comment by GammaGames** [comment]
Had to restructure to match the normal asset format (borrowed from https://github.com/GodotVR/godot-openvr-asset and https://github.com/Zylann/godot_heightmap_plugin)

**Comment by rpgwhitelock** [comment]
Seems to have the addons folder twice, as in `AllSkyFree_Godot\addons\AllSkyFree\addons\AllSkyFree\` Should it not just occur once `AllSkyFree_Godot\addons\AllSkyFree\` ?

**Comment by GammaGames** [comment]
Huh, yes it absolutely should. I'll  rebase and do it again tonight.

**Comment by aaronfranke** [comment]
@GammaGames Any update?

**Comment by GammaGames** [comment]
@aaronfranke whoops, I made the changes and forgot to make a request 🤦️ thank you 

#3

**Pull request closed without merging**
